### ISSUE TITLE
nodes_inventory

### ISSUE THREAD

**Issue by nabilovski** [davidban77/demo-ansible-gns3#1]
First, thank you for your effort  and for sharing with us your work David :).
I have tried to run lab_setup.yml playbook on my own topology but I had a problem which is with this dict:
nodes_inventory: "{{ hostvars['localhost']['nodes_inventory']['nodes_inventory'] }}"
I have tried to isolate it and see the debug of this value on my own topology which is just one router (ios):
ok: [R1] => {
    "<class 'dict'>": "VARIABLE IS NOT DEFINED!: "
what am I doing wrong, I am waiting for your suggestions :). Thanks

**Comment by davidban77** [comment]
Glad to be of help,

In order to troubleshoot more, if you have modified the playbook file can you share it?. Can you also share the inventory file?

Finally can you comment out the second playbook, and run the first section and debug the variable nodes_inventory? This is to see what is getting from the gns3 lab

**Comment by nabilovski** [comment]
This is the lab_setup.yml playbook after modification (I commented out the creation because I only have one router to test on ):

```yaml
# Play to setup GNS3 project and nodes, it retrieves their console information
- hosts: localhost
  gather_facts: no
  vars_files:
    - inventory/gns3_vars.yml
  collections:
    - davidban77.gns3

  tasks:
    - name: Lab creation and setup
      block:
       # - import_role:
       #     name: create_lab

        - name: Collect the nodes inventory
          gns3_nodes_inventory:
            url: "{{ gns3_url }}"
            project_name: "{{ gns3_project_name }}"
          register: nodes_inventory

        # - debug: var=nodes_inventory

    - name: Pause section
      when: boilerplate.config == "deploy" and boilerplate.automated_push == "no"
      pause:
        prompt: "Press Enter to proceed with configuration deployments:"

    - name: Pause section
      when: boilerplate.config == "deploy" and boilerplate.automated_push == "yes"
      pause:
        minutes: "{{ boilerplate.automated_push_delay | default(3) }}"

# Play that goes through the inventory devices to generate/push boiler plate config
- hosts: all
  gather_facts: no
  vars:
     ansible_connection: local
     ansible_python_interpreter: "{{ansible_playbook_python}}"
  vars_files:
    - inventory/gns3_vars.yml
  collections:
    - davidban77.gns3

  tasks:
    - name: Retrieving nodes inventory information
      set_fact:
        nodes_inventory: "{{ hostvars['localhost']['nodes_inventory']['nodes_inventory'] }}"
          # nodes_inventory: "{{ hostvars['localhost']['nodes_inventory'] }}"

    - name: Generate boilerplate config files
      when: boilerplate.config == "generate" and ansible_net_os != "gns3_builtin"
      block:
        - name: Create build folder
          file:
            path: "{{ playbook_dir }}/build"
            state: directory

        - name: Generate config
          template:
            src: templates/{{ ansible_net_os }}.j2
            dest: "{{ playbook_dir }}/build/{{ inventory_hostname }}-{{ ansible_net_os }}.conf"

    - name: Deploy boilerplate configuration
      when: boilerplate.config == "deploy" and ansible_net_os != "gns3_builtin"
      block:
        - name: Generate configuration variable
          set_fact:
            boilerplate_config: "{{ lookup('template', 'templates/{{ ansible_net_os }}.j2') }}"


        - name: "Push config"
          when: ansible_net_os == "ios" and image_style == "iosv_l3"
          gns3_telnet_console:
            remote_addr: "{{ nodes_inventory[inventory_hostname]['server'] }}"
            port: "{{ nodes_inventory[inventory_hostname]['console_port'] }}"
            send_newline: yes
            command: "{{ boilerplate_config.splitlines() }}"
            pause: 1
            timeout:
              general: 180
              pre_login: 60
              post_login: 60
              login_prompt: 30
              config_dialog: 30
```

and this is the output:

```shell
PLAY [all] ********************************************************************************************************

TASK [Retrieving nodes inventory information] *********************************************************************
ok: [R1]

TASK [Create build folder] ****************************************************************************************
skipping: [R1]

TASK [Generate config] ********************************************************************************************
skipping: [R1]

TASK [Generate configuration variable] ****************************************************************************
ok: [R1]

TASK [Push config] ************************************************************************************************
fatal: [R1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'R1'\n\nThe error appears to be in '/root/lab_setup.yml': line 71, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - name: \"Push config\"\n          ^ here\n"}

PLAY RECAP ********************************************************************************************************
R1                         : ok=2    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0 
```
